alias s:= switch

switch:
  sudo nix run nix-darwin -- switch --flake ~/.run_controls/.config/darwin#

nflake:
  $EDITOR ~/.run_controls/.config/darwin/flake.nix

nhome:
  $EDITOR ~/.run_controls/.config/darwin/home.nix
